# Generated by Django 4.1.2 on 2022-12-18 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_no', models.CharField(max_length=20)),
                ('awb_no', models.TextField(max_length=100)),
                ('delivery_server', models.CharField(max_length=254)),
            ],
        ),
    ]
